// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YMMO.Backend.Infrastructure.Data;

#nullable disable

namespace YMMO.Backend.Migrations
{
    [DbContext(typeof(YmmoDbContext))]
    [Migration("20260614025813_DockerDeployMigration")]
    partial class DockerDeployMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AgencyId");

                    b.HasIndex("LocationId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContactRole")
                        .HasColumnType("integer");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts", (string)null);

                    b.HasDiscriminator<string>("ContactType").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePriceUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropertyID")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusOffer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfferID");

                    b.HasIndex("AgentID");

                    b.HasIndex("ClientID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateListed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnergyClass")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Surface")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("PropertyId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("AgentId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SellerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.PropertyPicture", b =>
                {
                    b.Property<Guid>("PropertyPictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PropertyPictureId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyPicture");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.WishlistItem", b =>
                {
                    b.Property<Guid>("WishlistItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyID")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistItemID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("ClientID", "PropertyID")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agent", b =>
                {
                    b.HasBaseType("YMMO.Backend.Domain.Entities.Contact");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid");

                    b.HasIndex("AgencyId");

                    b.HasDiscriminator().HasValue("Agent");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("YMMO.Backend.Domain.Entities.Contact");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Criteria")
                        .HasColumnType("integer");

                    b.HasIndex("AgentId");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agency", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Location", "Location")
                        .WithMany("Agencies")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Offer", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agent", "Agent")
                        .WithMany("ManagedOffers")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Client")
                        .WithMany("Offers")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Property", "Property")
                        .WithMany("Offers")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Client");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Property", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agency", "Agency")
                        .WithMany("Properties")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Agent", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Buyer")
                        .WithMany("BoughtProperties")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YMMO.Backend.Domain.Entities.Location", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Seller")
                        .WithMany("OwnedProperties")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Agent");

                    b.Navigation("Buyer");

                    b.Navigation("Location");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.PropertyPicture", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Property", "Property")
                        .WithMany("Pictures")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.WishlistItem", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Client")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Property", "Property")
                        .WithMany("WishlistItems")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agent", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agency", "Agency")
                        .WithMany("Agents")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Client", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agent", "LinkedAgent")
                        .WithMany("LinkedClients")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedAgent");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Location", b =>
                {
                    b.Navigation("Agencies");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Property", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Pictures");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agent", b =>
                {
                    b.Navigation("LinkedClients");

                    b.Navigation("ManagedOffers");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Client", b =>
                {
                    b.Navigation("BoughtProperties");

                    b.Navigation("Offers");

                    b.Navigation("OwnedProperties");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
