// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YMMO.Backend.Infrastructure.Data;

#nullable disable

namespace YMMO.Backend.Migrations
{
    [DbContext(typeof(YmmoDbContext))]
    partial class YmmoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("AgencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AgencyID");

                    b.HasIndex("LocationID");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContactRole")
                        .HasColumnType("integer");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts", (string)null);

                    b.HasDiscriminator<string>("ContactType").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePriceUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropertyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfferID");

                    b.HasIndex("AgentID");

                    b.HasIndex("ClientID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgencyID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuyerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateListed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnergyClass")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LocationID")
                        .HasColumnType("uuid");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Surface")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("PropertyID");

                    b.HasIndex("AgencyID");

                    b.HasIndex("AgentID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("LocationID");

                    b.HasIndex("SellerID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.WishlistItem", b =>
                {
                    b.Property<Guid>("WishlistItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyID")
                        .HasColumnType("uuid");

                    b.HasKey("WishlistItemID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("ClientID", "PropertyID")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agent", b =>
                {
                    b.HasBaseType("YMMO.Backend.Domain.Entities.Contact");

                    b.Property<Guid>("AgencyID")
                        .HasColumnType("uuid");

                    b.HasIndex("AgencyID");

                    b.HasDiscriminator().HasValue("Agent");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("YMMO.Backend.Domain.Entities.Contact");

                    b.Property<Guid?>("AgentID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Criteria")
                        .HasColumnType("integer");

                    b.HasIndex("AgentID");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agency", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Location", "Location")
                        .WithMany("Agencies")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Offer", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agent", "Agent")
                        .WithMany("ManagedOffers")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Client")
                        .WithMany("Offers")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Property", "Property")
                        .WithMany("Offers")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Client");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Property", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agency", "Agency")
                        .WithMany("Properties")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Agent", "Agent")
                        .WithMany("SoldProperties")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Buyer")
                        .WithMany("BoughtProperties")
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YMMO.Backend.Domain.Entities.Location", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Seller")
                        .WithMany("OwnedProperties")
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Agent");

                    b.Navigation("Buyer");

                    b.Navigation("Location");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.WishlistItem", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Client", "Client")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YMMO.Backend.Domain.Entities.Property", "Property")
                        .WithMany("WishlistItems")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agent", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agency", "Agency")
                        .WithMany("Agents")
                        .HasForeignKey("AgencyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Client", b =>
                {
                    b.HasOne("YMMO.Backend.Domain.Entities.Agent", "LinkedAgent")
                        .WithMany("LinkedClients")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedAgent");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Location", b =>
                {
                    b.Navigation("Agencies");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Property", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Agent", b =>
                {
                    b.Navigation("LinkedClients");

                    b.Navigation("ManagedOffers");

                    b.Navigation("SoldProperties");
                });

            modelBuilder.Entity("YMMO.Backend.Domain.Entities.Client", b =>
                {
                    b.Navigation("BoughtProperties");

                    b.Navigation("Offers");

                    b.Navigation("OwnedProperties");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
